package it.polimi.ingsw.view;

import it.polimi.ingsw.model.events.Observer;
import it.polimi.ingsw.network.rmi.GameControllerWrapper;

/**
 * Generic client handler object.
 * A ClientHandler is a kind of Observer that sends the updates generated by the observed object
 * to the client.
 */
public interface ClientHandler extends Observer {
    /**
     * Allows to link the client handler to the game the client is playing.
     *
     * @param gameControllerWrapper the GameControllerWrapper object that contains a reference to the game the client is playing.
     */
    void setController(GameControllerWrapper gameControllerWrapper);
}
